- hosts: terraform-ansible
  become: True
  tasks:
    - name: Instalar Python3 e virtualenv
      apt:
        pkg:
          - python3
          - python3-venv
          - python3-pip
        update_cache: yes
